name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    main_project:
        name: ${{ matrix.actions.name }}

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: "Rector run"
                        run: vendor/bin/rector --ansi
                    -
                        name: "Composer Validate"
                        run: composer validate --strict --ansi

                    -
                        name: "Tests"
                        run: vendor/bin/phpunit

                    -
                        name: "Parse code"
                        run: vendor/bin/php-parse hello_world.php

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    coverage: none

            -   name: Install project Composer dependencies
                uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}
